services:
  - type: web
    name: Blog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Blog.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
