# Generated by Django 5.2.4 on 2025-08-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_blogpost_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
