# Generated by Django 5.2.4 on 2025-08-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_userprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
