# Generated by Django 5.2.5 on 2025-09-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_created',
        ),
    ]
